version: '3.5'

services:
  ingester:
    container_name: ingester
    image: chainlink/ingester
    build:
      context: ../../
      dockerfile: ingester/ingester.Dockerfile
    restart: always
    environment:
      - ETH_CHAIN_ID
      - ETH_URL
    depends_on:
      - node
      - explorer
